name: EMS System Simulator CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:18
        env:
          POSTGRES_DB: ems_sim_test_db
          POSTGRES_USER: ${{ secrets.DB_USER }}
          POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
        ports:
          -5432: 5432

    steps:
      - name: Checking out repository code
        uses: actions/checkout@v6

      - name: Configure
        run: cmake -S . -B build

      - name: Build
        run: cmake --build build

      - name: Test
        run: ctest --test-dir build
